FROM gcc:4.9
LABEL maintainer="Chengjun Jia <chengjunjiathu@outlook.com>"

# EXPOSE 4000

# COPY ./hexo-next /hexo-next
# WORKDIR /hexo-next

# RUN hexo g

# COPY ./id_rsa /root/.ssh/id_rsa
# RUN chmod 600 ~/.ssh/id_rsa
# RUN ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
